import { AppShell } from "@/components/AppShell";
const vars=[
  ["NEXT_PUBLIC_SUPABASE_URL","Supabase project URL","Required for persistence/evidence"],
  ["SUPABASE_SERVICE_ROLE_KEY","Supabase server key","Server only — never expose to browser"],
  ["OPENAI_API_KEY","OpenAI API key","AI requirement/test planner"],
  ["OPENAI_MODEL","gpt-5.6","Optional planner model override"],
  ["BROWSERBASE_API_KEY","Browserbase API key","Required for real isolated web execution"],
  ["BROWSERBASE_PROJECT_ID","Browserbase Project ID","Recommended by the Stagehand/Browserbase Next.js quickstart"],
];
export default function Setup(){return <AppShell active="setup"><div className="eyebrow">Vercel-ready deployment</div><h1 className="title">TestPilot AI Setup</h1><p className="muted lead">Push GitHub → Import into Vercel → add environment variables → deploy. No local browser runner is required for V1.1.1.</p><div className="two wideLeft sectionGap"><section className="card"><h2>1 · Supabase</h2><p className="muted">Create a Supabase project and run <code>supabase/schema.sql</code> once in SQL Editor. The script creates the TestPilot schema and the public evidence bucket.</p><h2>2 · Vercel Environment Variables</h2><div className="list">{vars.map(([k,v,d])=><div className="configRow" key={k}><code>{k}</code><div><b>{v}</b><small>{d}</small></div></div>)}</div></section><section className="card accentCard"><h2>3 · Deploy & verify</h2><ol className="setupList"><li>Push this repository to GitHub.</li><li>Import the repository in Vercel.</li><li>Use Node.js 24.x.</li><li>Add the environment variables.</li><li>Deploy.</li><li>Open <code>/api/health</code>.</li><li>Add a Project/target URL.</li><li>Generate a Test Plan and click Run.</li></ol><div className="notice"><b>Real execution</b><p>Browserbase launches the cloud Chromium session. Stagehand handles natural-language actions and extraction; the target app never runs on Boss's desktop.</p></div></section></div><section className="card sectionGap"><h2>Safety defaults</h2><div className="three"><div><b>Use UAT/Staging</b><p className="muted">Do not point autonomous execution at Production until explicit policies are added.</p></div><div><b>Dedicated test account</b><p className="muted">Use least-privilege accounts and data designed for automation.</p></div><div><b>Review evidence</b><p className="muted">PASS/FAIL is separate from human QA approval.</p></div></div></section></AppShell>}
