import { AppShell } from "@/components/AppShell";
const vars=[
  ["NEXT_PUBLIC_SUPABASE_URL","Supabase project URL","Required for persistence/evidence/Windows queue"],
  ["SUPABASE_SERVICE_ROLE_KEY","Supabase server key","Server only — never expose to browser or Windows VM"],
  ["OPENAI_API_KEY","OpenAI API key","Test planner + Windows semantic action resolver"],
  ["OPENAI_MODEL","gpt-5.6","Optional model override"],
  ["BROWSERBASE_API_KEY","Browserbase API key","Web Runner"],
  ["BROWSERBASE_PROJECT_ID","Browserbase Project ID","Web Runner project"],
  ["RUNNER_SHARED_SECRET","Long random secret","Authenticates Windows Agent ↔ Vercel API"],
];
export default function Setup(){return <AppShell active="setup"><div className="eyebrow">Vercel + Windows VM</div><h1 className="title">TestPilot AI V1.2 Setup</h1><p className="muted lead">The control plane stays Vercel-ready. Windows UI execution runs in a separate interactive Windows VM.</p>
<div className="two wideLeft sectionGap"><section className="card"><h2>1 · Supabase migration</h2><p className="muted">Run <code>supabase/schema.sql</code> again in SQL Editor. V1.2 appends idempotent runner/job tables and new Test Run columns.</p><h2>2 · Vercel Environment Variables</h2><div className="list">{vars.map(([k,v,d])=><div className="configRow" key={k}><code>{k}</code><div><b>{v}</b><small>{d}</small></div></div>)}</div></section>
<section className="card accentCard"><h2>3 · Windows Test VM</h2><ol className="setupList"><li>Use Windows 10/11 or Windows Server with Desktop Experience.</li><li>Keep a dedicated test user logged in and the desktop unlocked.</li><li>Copy the repository folder <code>windows-agent</code> to the VM.</li><li>Install .NET 10 SDK to build, or publish a self-contained <code>win-x64</code> binary.</li><li>Set <code>TESTPILOT_CONTROL_PLANE_URL</code> to your Vercel URL.</li><li>Set <code>TESTPILOT_RUNNER_SHARED_SECRET</code> to the same value as Vercel.</li><li>Run <code>scripts/install-startup.ps1</code> from the interactive test user.</li><li>Open <code>/runners</code> and confirm ONLINE.</li></ol><div className="notice warnBox"><b>Do not install the UI executor as a normal Windows Service.</b><p>Desktop UI automation must run in the logged-in interactive session. V1.2 uses an on-logon agent for that reason.</p></div></section></div>
<section className="card sectionGap"><h2>4 · Execute</h2><div className="three"><div><b>Web</b><p className="muted">Browserbase cloud Chromium remains supported from V1.1.1.</p></div><div><b>Windows</b><p className="muted">Vercel queues the test; an ONLINE Windows Agent claims it and drives WinForms with UIA3.</p></div><div><b>Evidence</b><p className="muted">Both platforms persist expected/actual and screenshot evidence into the same run history.</p></div></div></section></AppShell>}
